version: '3.8'

services:
  go:
    container_name: todo-app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./src
        target: /src